### PR TITLE
feat: Add today and now quickCommand

### PR DESCRIPTION
**Pull request by LintaoAmons**
Add two more commands

Also, I think maybe the `indent` and `auto-open a new line` is not necessary.

Cause maybe people(me) sometimes want just continue adding text right after the `quick command`(in the same line).

But I didn't include the change in this PR, cause I think it may not always the case for everybody

### CODE REVIEW

**Comment by LintaoAmons** [comment]
Eh, I pushed the second commit, you can decide whether or not to accept it. 

By the way, the use case is, I want 

`# /today` ---> `# 06/04/2022` 
instead of 
`# /today` ---> `# \n 06/04/2022`

**Comment by SeptemberHX** [comment]
I think the indent and new line are necessary for table and code block because they contains multiple lines, and each line should be indented:

```markdown
* Random words
    * Random words with indent
    
    | Header | Header | Header |
    | --- | --- | --- |
    |  |  |  |
```

* Random words
    * Random words with indent
    
    | Header | Header | Header |
    | --- | --- | --- |
    |  |  |  |

In this case, the indents are necessary otherwise the table is note rendered.

Maybe the best solution is explicitly declaring whether it is a 'block' style or 'inline' style.

**Comment by SeptemberHX** [comment]
I will merge this PR and add 'block' and 'inline' support latter.

**Comment by LintaoAmons** [comment]
Yeah~ Make sense. Can extend Hint type, one more field for `inline` or `block`

**Pull request merged**
